# Inference / evaluation configuration for fpsinet (updated defaults)
inference:
  # model checkpoint to load (relative or absolute)
  checkpoint: checkpoints/psinet_best_by_psnr.pth

  # Input: either a single image or a directory of noisy images
  input_path: r"D:\BaiduNetdiskDownload\LTCdata\after_2-4_16-30"
  # Optional: if you have corresponding clean images (for PSNR/SSIM), set clean_path (same filenames expected)
  clean_path: null

  # output
  output_dir: r"D:\BaiduNetdiskDownload\LTCdata\output"
  save_visuals: true
  save_individual: true
  save_residual: false

  # runtime/tiling
  device: cuda:0
  use_amp: true
  batch_size: 1
  patch: 0
  tile:
    enabled: false
    tile_size: 512
    overlap: 32

  # postprocess
  clamp_output: true
  convert_to_uint8: true

  # binary mode threshold (if model outputs single-channel logits and you want binarized output)
  threshold: 0.5

metrics:
  compute_psnr: true
  compute_ssim: true

tta:
  enabled: false
  transforms: ["hflip", "vflip"]

notes:
  # For binary outputs, after loading checkpoint you can compute:
  # pred_bin = (torch.sigmoid(out) > threshold).float()
