# Training configuration with new params forwarded to train.py
dataset:
  clean_dir: D:/BaiduNetdiskDownload/LTCdata/after_2-1_1-15_
  noisy_dir: D:/BaiduNetdiskDownload/LTCdata/after_2-4_1-15
  force_gray: false
  binarize_threshold: 0.5
  patch: 256
  val_split: 0.10
  num_workers: 8
  pin_memory: true
  synth_prob: 0.0

model:
  in_channels: 3
  out_channels: 1
  base_channels: 64
  growth_rate: 24
  rdb_layers: 4
  n_rdb_per_scale: 3
  n_scales: 4
  use_cbam: true
  lowfreq_mid: 256
  lowfreq_down: 5

training:
  epochs: 200
  batch_size: 8
  lr: 5e-5
  optimizer: adam
  weight_decay: 0.0
  amp: false
  seed: 42
  out_dir: checkpoints
  save_every: 1
  save_best_by: psnr
  resume: r"C:\Users\Administrator\fpsinet\checkpoints\psinet_epoch54.pth"

losses:
  lambda_l1: 1.0
  lambda_lowfreq: 0.5
  lambda_tv: 0.01
  lambda_fft: 0.05
  lambda_perc: 0.0
  lambda_ssim: 0.01
  lambda_highfreq: 1.0
  lambda_edge: 0.5
  lambda_gate: 0.2

extra:
  binary_output: true
  region_weight: 3.0
  lowfreq_blur_sigma: 2.0
  clip_grad: 1.0

scheduler:
  type: ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 6
  verbose: true

logging:
  vis_dir: checkpoints/vis
  log_interval_steps: 50
  val_interval_epochs: 1
